---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
      #storageClassName: nfs-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 5
  selector:
    matchLabels:
        app: tspproject
        tier: test
  template:
    metadata:
      labels:
        app: tspproject
        tier: test
    spec:
      containers:
        - name: myfrontend
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: db-pv
      volumes:
        - name: db-pv
          persistentVolumeClaim:
            claimName: db-pvc
     
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: tspproject
    tier: test
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: tspproject
    tier: test