---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
    tier: test
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: {{ .Values.service.type }}
  ports:
    # the port that this service should serve on
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app_name }}
    tier: test
